apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul
  labels:
    app: consul
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
  annotations:
  name: consul-metrics-role
  namespace:
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  name: consul-metrics-rolebinding
  namespace:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: consul-metrics-role
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring-system
---
apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  ports:
  - port: 8500
    name: http
  selector:
    app: consul
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
  namespace:
  labels:
spec:
  serviceName: consul
  replicas: 3
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      serviceAccountName: consul
      terminationGracePeriodSeconds: 10
      containers:
        - name: node
          image: consul:latest
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: data
              mountPath: /consul/data
          args:
          - consul
          - agent
          - -datacenter=kubernetes
          - -log-level=debug
          - -bootstrap-expect=3
          - -retry-join=provider="k8s" namespace="$(POD_NAMESPACE)" label_selector="app=consul"
          - -client=0.0.0.0
          - -bind=0.0.0.0
          - -data-dir=/consul/data
          - -server
          - -domain=cluster.local
          - -ui
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "consul leave"]
        - name: exporter
          image: prom/consul-exporter:latest
          args:
          - --consul.server=localhost:8500
          - --log.level=debug
          ports:
          - containerPort: 9107          
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        #storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: consul
  name: consul-metrics
  namespace:
spec:
  ports:
  - port: 9107
    name: consul-metrics
  selector:
    app: consul
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: consul
  namespace:
spec:
  endpoints:
  - interval: 15s
    port: consul-metrics
    path: /metrics
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - adriano # put here the current namespace
  selector:
    matchLabels:
      app.kubernetes.io/name: consul
# sum by (node) (consul_catalog_service_node_healthy)