apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    run: nginx
spec:
  ports:
  - protocol: TCP
    # this is the service port!!!
    port: 80 # by convention, the service port is also used by the load-balancer as its public port
    targetPort: 80
    #nodePort: 30000
  selector:
    run: nginx
  type: LoadBalancer
