apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    key: value
spec:
  restartPolicy: Always
  containers:
  - name: nginx
    image: nginx:1.21.3
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 8Gi
      requests:
        cpu: 100m
        memory: 500Mi
