apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    #ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: argocd.training.clastix.io
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: https
