apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wordpress
spec:
  rules:
  - host: blog.training.clastix.io
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress 
          servicePort: 80