apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapp
  annotations:
spec:
  rules:
  - host: webapp.training.clastix.io
    http:
      paths:
      - path: /
        backend:
          serviceName: nodejs
          servicePort: 8080
