apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace:
  name: minio
spec:
  rules:
  - host: minio.training.clastix.io
    http:
      paths:
      - path: /
        backend:
          serviceName: minio
          servicePort: 9000
