apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
  annotations:
  name: webapp-metrics-role
  namespace:
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
  name: webapp-metrics-rolebinding
  namespace:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webapp-metrics-role
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring-system
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app.kubernetes.io/name: webapp
  namespace:
spec:
  # Can be specified for headless services when proxying is not required
  # clusterIP: None  
  ports:
  - name: root
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: metrics
    protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    run: webapp
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webapp
  namespace:
spec:
  endpoints:
  - interval: 15s
    port: metrics
    path: /metrics
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - namespace00 # put here the current namespace
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp

