apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
  namespace:
  name: webapp-blue
spec:
  replicas: 6
  selector:
    matchLabels:
      run: webapp
      version: v1.0.0
  template:
    metadata:
      labels:
        run: webapp
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - image: bsctl/go-web-app:latest
        name: webapp
        env:
        - name: VERSION
          value: v1.0.0
        ports:
        - name: root
          containerPort: 8080
          protocol: TCP
        - name: probe
          containerPort: 8090
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ready
            port: 8090
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /live
            port: 8090
            scheme: HTTP
          periodSeconds: 15
